routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@_index')->name('home');

Route::get('/search', 'Keyword\KeywordViewController@_searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@_autocomplete')->name('search_autocomplete');
Route::post('/related-keyword', 'Keyword\KeywordViewController@_relatedKeyword');
// add route post_faq
Route::post('/faq/{id_kw}/{id_q}', 'Keyword\KeywordViewController@_postFAQs')->name('post_faq');

Route::get('/more-info/{domain?}', 'Keyword\KeywordViewController@_moreOffers');

Route::get('/v-result/{result_id?}', 'Keyword\KeywordViewController@_outLink')->name('result_out');

Route::get('/blog/{slug?}', 'Posts\PostViewController@_blog')->name('blog');
Route::post('/saving-email', 'HomeController@_savingEmail')->name('saveEmail');

Route::get('/sitemap-job/xml/{file_name}', 'SiteMapController@_sitemapDynamic');

Route::get('/store/{slug}','Store\StoreViewController@stores')->name('stores');

Route::get('/clear-cache-ar', function () {
    $exitCode = \Illuminate\Support\Facades\Artisan::call('config:clear');
    $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
    return 'DONE'; //Return anything
});
Auth::routes();
Route::group(['prefix' => 'c-panel', 'as' => 'cpanel.'], function () {
    Route::get('/', 'DashboardController@index')->name('home-dashboard');
    Route::get('/clear-cache', function () {
        $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
        return view('cpanel.cache_clear');
    });

    Route::resource('tags', 'Tags\CmsTagsController');
    Route::post('tags/{id}', 'Tags\CmsTagsController@update');
    Route::post('tags-table', 'Tags\CmsTagsController@index')->name('tags.table');

    Route::resource('tags_kw', 'Tags\TagsKWController');
    Route::post('tags_kw/{id}', 'Tags\TagsKWController@update');
    Route::post('tags_kw-effect', 'Tags\TagsKWController@_checkEffect');
    Route::post('tags_kw-table', 'Tags\TagsKWController@index')->name('tags_kw.table');

    Route::resource('emails', 'EmailController');
    Route::get('email-send', 'EmailController@_sendEmail')->name('email.get-send');
    Route::post('email-send', 'EmailController@_sendEmail')->name('email.post-send');
    Route::post('emails-table', 'EmailController@show_svs')->name('emails.show_table');

    Route::resource('categories', 'CategoriesController');
    Route::post('ajax-categories', 'CategoriesController@show_svs')->name('svs_categories');

    Route::resource('config-site', 'CmsConfigController');
 
    Route::resource('keywords', 'Keyword\CmsKeysController');
    Route::post('keywords/{id}', 'Keyword\CmsKeysController@update');
    Route::get('add-kw-excel', 'Keyword\CmsKeysController@_vAddExcel');
    Route::post('add-kw-excel', 'Keyword\CmsKeysController@_addExcel')->name('add_kw_excel');
    Route::post('add-kw-txt', 'Keyword\CmsKeysController@_addTXT');

    Route::get('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('get-remove-keyword');
    Route::post('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('post-remove-keyword');
    Route::post('ajax-keyword-black', 'BlacklistController@show_svs_kw')->name('svs_keyword_black');

    Route::post('ajax-keywords', 'Keyword\CmsKeysController@show_svs')->name('svs_keywords');
    Route::get('add-connect', 'Keyword\CmsKeysController@_vAddCUT');
    Route::post('add-connect', 'Keyword\CmsKeysController@_pAddCUT')->name('add_connect');
    Route::get('add-connect-store', 'Keyword\CmsKeysController@_connectToStore');
    Route::post('add-connect-store', 'Keyword\CmsKeysController@_pConnectToStore')->name('add_connect_store');

    Route::post('/daterange/kw_crawled', 'Keyword\CmsKeysController@kw_crawled')->name('daterange.kw_crawled');

    Route::resource('posts', 'Posts\CmsPostController');
    Route::post('posts/{id}', 'Posts\CmsPostController@update');
    Route::post('ajax-posts', 'Posts\CmsPostController@show_svs')->name('svs_posts');

    

    
    Route::get('add-excel', 'Store\CmsStoreController@add')->name('stores.add_excel');
    Route::post('add-excel/stores', 'Store\CmsStoreController@_addTXT')->name('stores.add_excel_post');
    Route::get('export-excel', 'Store\CmsStoreController@export')->name('stores.export_excel');
    Route::post('export-excel', 'Store\CmsStoreController@_pexportAllURL')->name('stores.p_export');
    Route::post('store-remove/{id}', 'Store\CmsStoreController@destroy')->name('stores.destroy');
    Route::resource('stores', 'Store\CmsStoreController');
    Route::post('stores/{id}', 'Store\CmsStoreController@update');
    Route::post('ajax-stores', 'Store\CmsStoreController@svs_store')->name('all_stores');
    // route update stt
    Route::post('/update-store-stt','Store\CmsStoreController@_updateStt');


    Route::resource('syncs', 'Store\SyncsController');
    Route::post('syncs/{id}', 'Store\SyncsController@update');
    Route::post('all-sync','Store\SyncsController@stores_svs')->name('all_sync');

    Route::post('/sync-one','Store\SyncsController@_SyncOne');
    Route::post('/sync-start','Store\SyncsController@_startSync');
    Route::get('/sync-start','Store\SyncsController@_gstartSync');

    Route::resource('blacklist', 'BlacklistController');
    Route::post('ajax-blacklist', 'BlacklistController@show_svs')->name('svs_blacklist');

    Route::get('clear-cache/{cache_option?}/{slug_cache?}', 'CacheController@_clearCache');

    Route::get('run-bot', 'ScraperController@_index')->name('run_bot_keywords');

    Route::post('other-get-info', 'ScraperController@_getOtherInfo');
    Route::post('track-control', 'ScraperController@_trackControl');
    Route::post('track-bing', 'ScraperController@_bingPost')->name('bing_scraper');
    Route::post('track-google', 'ScraperController@_googleScraper')->name('google_scraper');
    Route::post('track-amz', 'ScraperController@_amzScraper')->name('amz_scraper');

    Route::get('bot-multi', 'ScraperController@_vBotMulti')->name('bot_multi');
    Route::post('get-keyword', 'ScraperController@_getKeyword');
    Route::post('add-2-sitemap', 'ScraperController@_add2Sitemap');

    Route::get('file-manager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('file-manager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');

});

Route::get('/{slug?}', 'Keyword\KeywordViewController@_viewKeyword')->name('v_keyword');

/*Migration DB
php artisan migrate --path=/database/migrations/2019_08_28_152107_create_categories_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_150242_create_spam_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_152854_create_results_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_151618_create_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_131221_create_coupons_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_135230_create_keys_related.php
db.categories.getIndexes();
*/

app/Http/Controllers/Store/CmsCouponController.php
<?php

namespace App\Http\Controllers\Store;

use App\Stores;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Coupons;
use Illuminate\Support\Facades\Cache;
use MongoDB\BSON\ObjectId;
use MongoDB\BSON\UTCDateTime as MongoUTC;
use App\Http\Controllers\Controller;

class CmsCouponController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $cache_time = 1;
    private $auth_logged;

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $auth_logged = Auth::user()->email;
        return view('cpanel.coupons.index_table');
    }

    public function coupon_table()
    {
        return view('cpanel.coupons.index_table');
    }

    protected function coupons_svs(Request $request)
    {
        $columns = array(
            0 => 'order_index',
            1 => 'code_type',
            2 => 'coupon_name',
            3 => 'coupon_code',
            4 => 'expired_date',
            5 => 'update_at',
            6 => 'options',
        );

        $limit = intval($request->input('length'));
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        $hash = md5($limit . $start . $order . $dir . date("H"));
        $totalData = Cache::remember('totalData' . $hash, $this->cache_time, function () {
            return Coupons::count();
        });
        $totalFiltered = $totalData;

        if (empty($request->input('search.value'))) {
            $posts = Cache::remember('posts' . $hash, $this->cache_time, function () use ($limit, $order, $dir, $start) {
                return Coupons::with('stores')->offset(intval($start))
                    ->take($limit)
                    ->orderBy($order, $dir)
                    ->get();
            });
        } else {
            $search = $request->input('search.value');
            $slug_store = slugify($search);
            $hash = md5($limit . $start . $order . $dir . date("H") . $search);
            $posts = Cache::remember('posts' . $hash, $this->cache_time, function () use ($limit, $order, $dir, $start, $search) {
                return Coupons::with('stores')->where('forStore', 'LIKE', "%{$search}%")
                    ->orWhere('coupon_name', 'LIKE', "%{$search}%")
                    ->orWhere('coupon_code', 'LIKE', "%{$search}%")
                    ->offset(intval($start))
                    ->take($limit)
                    ->orderBy($order, $dir)
                    ->get();
            });

            $totalFiltered = Cache::remember('totalFiltered' . $hash, $this->cache_time, function () use ($search) {
                return Coupons::where('forStore', 'LIKE', "%{$search}%")
                    ->orWhere('coupon_name', 'LIKE', "%{$search}%")
                    ->orWhere('coupon_code', 'LIKE', "%{$search}%")
                    ->count();
            });
        }

        $data = array();
        if (!empty($posts)) {
            foreach ($posts as $post) {
                if ($post['order_index'] > 0) {
                    $nestedData['order_index'] = '<span class="label label-success">Order ' . $post['order_index'] . '</span>';
                } else {
                    $nestedData['order_index'] = '<span class="label label-default">Normal</span>';
                }
                $nestedData['code_type'] = ucwords($post['code_type']);
                $nestedData['coupon_name'] = '<a title="Edit coupon: ' . $post['coupon_name'] . '" href="' . route('cpanel.coupons.edit', ['id' => $post['coupon_slug']]) . '">' . $post['coupon_name'] . ' <i class="fa fa-edit"></i></a> <br/>
					Store: <a class="text-red" href="/stores/' . $post['forStore'] . '" target="_blank"
                           title="Go to ' . $post->stores['store_name'] . '">' . $post->stores['store_name'] . '</a> - Id Coupons:' . $post['_id'];
                $nestedData['coupon_code'] = $post['coupon_code'];
                if ($post['expired_date']) {
                    try {
                        $nestedData['expired_date'] = date('Y-m-d', intval($post['expired_date']));
                    } catch (\Exception $e) {
                        $nestedData['expired_date'] = $post['expired_date'];
                    }
                } else {
                    $nestedData['expired_date'] = '<span class="label label-default">not_expired</span>';
                }
                $nestedData['updated_at'] = 'Created at:' . Carbon::parse($post['created_at'])->format('d-m-Y H:m:s') . '<br/>Updated at:' . Carbon::parse($post['updated_at'])->format('d-m-Y H:m:s') . '<br/><small>by:' . $post['created_by'] . '</small>';
                $nestedData['options'] = '<a href="' . route('cpanel.coupons.destroy', $post['coupon_slug']) . '" data-id="' . $post['coupon_slug'] . '" data-name="' . $post['coupon_name'] . '" data-method="delete" class="jquery-postback"><span class="label label-danger"><i class="fa fa-remove"></i></span></a>';
                $nestedData['_id'] = $post['_id'];
                $data[] = $nestedData;
            }
        }

        $json_data = array(
            "draw" => intval($request->input('draw')),
            "recordsTotal" => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data" => $data
        );

        echo json_encode($json_data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    private function _uniqueStr()
    {
        $characters = '1234567890';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < 13; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    public function create()
    {
        //
        return view('cpanel.coupons.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        //
        $auth_logged = Auth::user()->email;
        //if (Auth::user()->hasPermissionTo('add-coupon')) {
        $slug = $this->_uniqueStr();
        if ($request->input('expired_date') == '') {
            $expired_date = false;
        } else {
            $expired_date = strtotime($request->input('expired_date') . " 23:59:59");
        }
        DB::collection('coupons')->insert(
            [
                'coupon_name' => $request->input('coupon_name'),
                'coupon_excerpt' => $request->input('coupon_excerpt'),
                'coupon_code' => $request->input('coupon_code'),
                'code_status' => intval($request->input('code_status')),
                'off_sale' => intval($request->input('off_sale')),
                'off_type' => $request->input('off_type'),
                'code_type' => $request->input('code_type'),
                'expired_date' => $expired_date,
                'forStore' => $request->input('forStore'),
                'aff_link' => $request->input('aff_link'),
                'order_index' => intval($request->input('order_index')),
                'coupon_slug' => $slug,
                'created_at' => new MongoUTC(strtotime('now') * 1000),
                'created_by' => $auth_logged,
                'update_at' => strtotime("now"),
            ]
        );
        Stores::where('slug_store', trim($request->input('forStore')))->increment('coupon_added');
        //DB::collection('stores')->where('slug_store', $request->input('forStore'))->increment('coupon_added');
        $msg = "Created coupon";
        return redirect()->route('cpanel.coupons.index', ['msg' => $msg]);
        //}
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        //
        $coupon_edit = Coupons::where('coupon_slug', $id)->first();
        return view('cpanel.coupons.edit', compact(array('coupon_edit')));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        //
        $auth_logged = Auth::user()->email;
        if ($request->input('expired_date') == '') {
            $expired_date = false;
        } else {
            $expired_date = strtotime($request->input('expired_date') . " 23:59:59");
        }
        Coupons::where('coupon_slug', $id)
            ->update([
                'coupon_name' => $request->input('coupon_name'),
                'coupon_excerpt' => $request->input('coupon_excerpt'),
                'coupon_code' => $request->input('coupon_code'),
                'code_status' => intval($request->input('code_status')),
                'off_sale' => intval($request->input('off_sale')),
                'off_type' => $request->input('off_type'),
                'code_type' => $request->input('code_type'),
                'expired_date' => $expired_date,
                'order_index' => intval($request->input('order_index')),
                'forStore' => $request->input('forStore'),
                'aff_link' => $request->input('aff_link'),
                'update_at' => strtotime("now"),
                'created_by' => $auth_logged,
            ]);
        $msg = "Update coupon:" . $request->input('coupon_name');

resources/views/cpanel/stores/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Add New Store Brand</h1>
@stop

@section('content')
    <div class="col-md-8">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            {!! Form::open(['route' => 'cpanel.stores.store']) !!}
            {!! Form::token(); !!}
            <div class="box-body">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" name="active_stt" id="active_stt">
                    <label class="custom-control-label" for="active_stt">Active Store</label>
                </div>
                <div class="form-group">
                    <label for="store_name">Connect ID</label>
                    <input type="text" class="form-control" name="connect_id" id="connect_id"
                           placeholder="Id from UPTO" value="">
                </div>
                <div class="form-group">
                    <label for="store_name">Store Name</label>
                    <input type="text" class="form-control" name="store_name" id="store_name"
                           placeholder="Enter Store Name Example:Adidas">
                </div>
                <div class="form-group">
                    <label for="store_domain">Store Domain</label>
                    <input type="text" class="form-control" name="store_domain" id="store_domain"
                           placeholder="Enter Store Domain Example:Adidas.com">
                </div>
                <div class="form-group">
                    <label for="store_excerpt">Store Excerpt</label>
                    <input type="text" class="form-control" name="store_excerpt" id="store_excerpt"
                           placeholder="Store Excerpt">
                </div>
                <div class="form-group">
                    <label>Of Category</label>
                    <select multiple="" class="form-control" name="store_cat[]">
                        @foreach($categories as $category)
                            <option value="{{$category['slug']}}">{{$category['name']}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="store_image">Store Thumbnail</label>
                    <div class="input-group">
                    <span class="input-group-btn">
                        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                            <i class="fa fa-picture-o"></i> Choose
                     </a>
                    </span>
                        <input id="thumbnail" class="form-control" type="text" name="store_image">
                    </div>
                    <img id="holder" style="margin-top:15px;max-height:100px;">
                </div>
                <div class="form-group">
                    <label for="store_aff">Store Link Affiliate</label>
                    <input type="text" class="form-control" name="store_aff" id="store_aff"
                           placeholder="Store Aff">
                </div>
                <div class="form-group">
                    <label>Rich Content</label>
                    <textarea class="form-control" id="rich_content" name="rich_content" rows="5"
                              placeholder="Enter ..."></textarea>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
    

@stop
@section('js')
    <script src="{{asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script>
    <script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
    <script>
        var domain = "/c-panel/file-manager";
        $('#lfm').filemanager('image', {prefix: domain});
        var options = {
            filebrowserImageBrowseUrl: '/c-panel/file-manager?type=Images',
            filebrowserImageUploadUrl: '/c-panel/file-manager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/c-panel/file-manager?type=Files',
            filebrowserUploadUrl: '/c-panel/file-manager/upload?type=Files&_token='
        };

        $(document).ready(function () {
            CKEDITOR.replace('rich_content', options);
        });
    </script>
@endsection

resources/views/cpanel/stores/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1><i class="fa fa-shopping-cart"></i> List Store</h1>
    <ol class="breadcrumb">
        <li><a href="/c-panel"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#" class="active">Stores</a></li>
    </ol>
    <br/>
    <a class="btn btn-success" href="{{route('c-panel.stores.create')}}">
        <i class=" fa fa-plus-circle"></i>
        Create New Store
    </a>
    <a class="btn btn-danger" href="{{route('c-panel.stores.add_excel')}}">
        <i class=" fa fa-plus-circle"></i>
        Add Stores By Excel File
    </a>
    <a class="btn btn-warning" href="{{route('c-panel.stores.export_excel')}}">
        <i class=" fa fa-plus-circle"></i>
        Export Stores By Excel 2003
    </a>
@stop

@section('content')
    @isset ($msg)
        <div class="alert alert-success">
            <p>{{ $msg }}</p>
        </div>
    @endisset
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Store Image</th>
                <th>Store Name</th>
                <th>Add/Update Date</th>
                <th>Created At</th>
                <th>-</th>
            </tr>
            </thead>
            <tbody>
            @foreach($stores as $store)
                <tr id="{{$store['_id']}}">
                    <td>
                        <a href="{{$store['store_domain']}}" target="_blank">
                            <img height="80px" class="lazyload"
                                 data-original="{{$store['store_image']}}"
                                 src="/photos/goodinfohome-loading.png"
                                 alt="{{str_title($store['store_name'])}}"/>
                        </a>
                    </td>
                    <td>
                        {{$store['store_name']}} -
                        <a href="{{$store['store_aff']}}" target="_blank"><i class="fa fa-money"></i></a>
                         -
                        <a href="/coupons/{{$store['slug_store']}}" target="_blank"><i class="fa fa-external-link"></i></a>
                    </td>
                    <td>{{$store['coupon_added']}}</td>
                    <td>Created at: {{Carbon\Carbon::parse($store['created_at'])->format('Y-m-d H:m:s')}}<br/>
                    Updated at: {{Carbon\Carbon::parse($store['updated_at'])->format('Y-m-d H:m:s')}}
					</td>
                    <td>
                        <a href="{{route('c-panel.stores.edit',['id' =>  $store['_id'] ])}}"><span class="label label-primary"><i class="fa fa-edit"></i></span></a>
                        <a href="{{ route('c-panel.stores.destroy', $store['_id']) }}" data-id-store="{{$store['_id']}}" data-store="{{$store['name']}}" data-method="delete" class="jquery-postback"><span class="label label-danger"><i class="fa fa-remove"></i></span></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop
@section('js')
    <script src="{{asset('/js/jquery.lazyload.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#data-table').DataTable({
                "drawCallback": function() {
                    $("img.lazyload").lazyload();
                }
            });
            $("img.lazyload").lazyload({
                threshold: 200
            });
        });
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
            }
        });
        $(document).on('click', 'a.jquery-postback', function (e) {
            e.preventDefault(); // does not go through with the link.

            var $this = $(this);
            var name_store = $(this).data('store');
            var id_store = $(this).data('id-store');
            console.log($(this).data('store'));
            $.post({
                type: $this.data('method'),
                url: $this.attr('href')
            }).done(function (data) {
                alert('Success remove: ' + name_store);
                $("#" + id_store).hide();
            });
        });
    </script>
@endsection

resources/views/cpanel/stores/index_table.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1><i class="fa fa-shopping-cart"></i> List Store</h1>
    <ol class="breadcrumb">
        <li><a href="/c-panel"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#" class="active">Stores</a></li>
    </ol>
    <br/>
    <a class="btn btn-success" href="{{route('cpanel.stores.create')}}">
        <i class=" fa fa-plus-circle"></i>
        Create New Store
    </a>
    <a class="btn btn-danger" href="{{route('cpanel.stores.add_excel')}}">
        <i class=" fa fa-plus-circle"></i>
        Add Stores By Excel File
    </a>
    <a class="btn btn-warning" href="{{route('cpanel.stores.export_excel')}}">
        <i class=" fa fa-plus-circle"></i>
        Export Stores By Excel 2003
    </a>
    <a class="btn btn-primary" href="/c-panel/net-api">
        <i class=" fa fa-plus-circle"></i>
        Sync Stores & Coupons From NET
    </a>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
@stop

@section('content')
    @isset ($msg)
        <div class="alert alert-success">
            <p>{{ $msg }}</p>
        </div>
    @endisset
    <div class="table-responsive">
        <div class="form-group">
            <label class="radio-inline"><input type="radio" name="filter_with" value="all">All Stores</label>
            <label class="radio-inline"><input type="radio" name="filter_with" value="sharesale">Net ShareSale</label>
        </div>
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Store Image</th>
                <th>Store Name</th>
                <th>Coupons added</th>
                <th>Created At</th>
                <th>-</th>
            </tr>
            </thead>
        </table>
    </div>
@endsection
@section('js')
    <script src="{{asset('/js/jquery.lazyload.min.js')}}"></script>
    <script>
        const urlParams = new URLSearchParams(window.location.search);
        let filter_with = urlParams.get('filter_with');
        if (typeof filter_with === "undefined") {
            filter_with = $('input[type=radio][name=filter_with]').val();
        }
        $('input[type=radio][name=filter_with]').change(function () {
            filter_with = this.value;
            window.open('http://' + window.location.hostname + window.location.pathname + '?filter_with=' + filter_with, '_self');
        });
        
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
           
            $('#data-table').DataTable({
                "processing": true,
                "serverSide": true,
                "columnDefs": [
                    {"orderable": false, "targets": [0, 1, 2, 4]}
                ],
                "ajax": {
                    "url": "{{ route('cpanel.all_stores') }}?filter_with=" + filter_with,
                    "dataType": "json",
                    "type": "POST",
                    "data": {_token: "{{csrf_token()}}"}
                },
                "columns": [
                    {"data": "store_image"},
                    {"data": "store_name"},
                    {"data": "coupon_added"},
                    {"data": "created_at"},
                    {"data": "options"}
                ],
                "drawCallback": function () {
                    $("img.lazyload").lazyload();
                }
            });
            $("img.lazyload").lazyload({
                threshold: 200
            });
        });
        $('.active_stt').change(function () {
            alert('changed');
            let params = {};
            params.id = $(this).data('id');
            if ($(this).is(':checked')) {
                params.active_stt = 1;
            } else {
                params.active_stt = 0;
            }
            $.post({
                type: 'POST',
                url: '/c-panel/update-store-stt',
                data: params
            }).done(function (data) {
                alert(JSON.stringify(data));
            });
        })

        $(document).on('click', 'a.jquery-postback', function (e) {
            e.preventDefault(); // does not go through with the link.
            let $this = $(this),
                from_collection = $(this).data('from_collection'),
                id_store = $(this).data('id-store'),
                name_store = $(this).data('store');
            if (typeof from_collection !== "undefined") {
                $this.find('i').addClass('fa-spin');
                $.post({
                    type: $this.data('method'),
                    url: $this.attr('href'),
                    data: {id: id_store, from_collection: from_collection}
                }).done(function (data) {
                    $this.find('i').removeClass('fa-spin');
                    alert(JSON.stringify(data));
                });
            } else {
                console.log($(this).data('store'));
                $.post({
                    type: $this.data('method'),
                    url: $this.attr('href')
                }).done(function (data) {
                    alert('Success remove: ' + name_store);
                    $("#" + id_store).hide();
                });
            }
        });
    </script>
@endsection