routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@_index')->name('home');

Route::get('/search', 'Keyword\KeywordViewController@_searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@_autocomplete')->name('search_autocomplete');
Route::post('/related-keyword', 'Keyword\KeywordViewController@_relatedKeyword');
// add route post_faq
Route::post('/faq/{id_kw}/{id_q}', 'Keyword\KeywordViewController@_postFAQs')->name('post_faq');

Route::get('/more-info/{domain?}', 'Keyword\KeywordViewController@_moreOffers');

Route::get('/v-result/{result_id?}', 'Keyword\KeywordViewController@_outLink')->name('result_out');

Route::get('/blog/{slug?}', 'Posts\PostViewController@_blog')->name('blog');
Route::post('/saving-email', 'HomeController@_savingEmail')->name('saveEmail');

Route::get('/sitemap-job/xml/{file_name}', 'SiteMapController@_sitemapDynamic');

Route::get('/store/{slug}','Store\StoreViewController@stores')->name('stores');

Route::get('/clear-cache-ar', function () {
    $exitCode = \Illuminate\Support\Facades\Artisan::call('config:clear');
    $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
    return 'DONE'; //Return anything
});
Auth::routes();
Route::group(['prefix' => 'c-panel', 'as' => 'cpanel.'], function () {
    Route::get('/', 'DashboardController@index')->name('home-dashboard');
    Route::get('/clear-cache', function () {
        $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
        return view('cpanel.cache_clear');
    });

    Route::resource('tags', 'Tags\CmsTagsController');
    Route::post('tags/{id}', 'Tags\CmsTagsController@update');
    Route::post('tags-table', 'Tags\CmsTagsController@index')->name('tags.table');

    Route::resource('tags_kw', 'Tags\TagsKWController');
    Route::post('tags_kw/{id}', 'Tags\TagsKWController@update');
    Route::post('tags_kw-effect', 'Tags\TagsKWController@_checkEffect');
    Route::post('tags_kw-table', 'Tags\TagsKWController@index')->name('tags_kw.table');

    Route::resource('emails', 'EmailController');
    Route::get('email-send', 'EmailController@_sendEmail')->name('email.get-send');
    Route::post('email-send', 'EmailController@_sendEmail')->name('email.post-send');
    Route::post('emails-table', 'EmailController@show_svs')->name('emails.show_table');

    Route::resource('categories', 'CategoriesController');
    Route::post('ajax-categories', 'CategoriesController@show_svs')->name('svs_categories');

    Route::resource('config-site', 'CmsConfigController');
 
    Route::resource('keywords', 'Keyword\CmsKeysController');
    Route::post('keywords/{id}', 'Keyword\CmsKeysController@update');
    Route::get('add-kw-excel', 'Keyword\CmsKeysController@_vAddExcel');
    Route::post('add-kw-excel', 'Keyword\CmsKeysController@_addExcel')->name('add_kw_excel');
    Route::post('add-kw-txt', 'Keyword\CmsKeysController@_addTXT');

    Route::get('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('get-remove-keyword');
    Route::post('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('post-remove-keyword');
    Route::post('ajax-keyword-black', 'BlacklistController@show_svs_kw')->name('svs_keyword_black');

    Route::post('ajax-keywords', 'Keyword\CmsKeysController@show_svs')->name('svs_keywords');
    Route::get('add-connect', 'Keyword\CmsKeysController@_vAddCUT');
    Route::post('add-connect', 'Keyword\CmsKeysController@_pAddCUT')->name('add_connect');
    Route::get('add-connect-store', 'Keyword\CmsKeysController@_connectToStore');
    Route::post('add-connect-store', 'Keyword\CmsKeysController@_pConnectToStore')->name('add_connect_store');

    Route::post('/daterange/kw_crawled', 'Keyword\CmsKeysController@kw_crawled')->name('daterange.kw_crawled');

    Route::resource('posts', 'Posts\CmsPostController');
    Route::post('posts/{id}', 'Posts\CmsPostController@update');
    Route::post('ajax-posts', 'Posts\CmsPostController@show_svs')->name('svs_posts');

    

    
    Route::get('add-excel', 'Store\CmsStoreController@add')->name('stores.add_excel');
    Route::post('add-excel/stores', 'Store\CmsStoreController@_addTXT')->name('stores.add_excel_post');
    Route::get('export-excel', 'Store\CmsStoreController@export')->name('stores.export_excel');
    Route::post('export-excel', 'Store\CmsStoreController@_pexportAllURL')->name('stores.p_export');
    Route::post('store-remove/{id}', 'Store\CmsStoreController@destroy')->name('stores.destroy');
    Route::resource('stores', 'Store\CmsStoreController');
    Route::post('stores/{id}', 'Store\CmsStoreController@update');
    Route::post('ajax-stores', 'Store\CmsStoreController@svs_store')->name('all_stores');
    // route update stt
    Route::post('/update-store-stt','Store\CmsStoreController@_updateStt');


    Route::resource('syncs', 'Store\SyncsController');
    Route::post('syncs/{id}', 'Store\SyncsController@update');
    Route::post('all-sync','Store\SyncsController@stores_svs')->name('all_sync');

    Route::post('/sync-one','Store\SyncsController@_SyncOne');
    Route::post('/sync-start','Store\SyncsController@_startSync');
    Route::get('/sync-start','Store\SyncsController@_gstartSync');

    Route::resource('blacklist', 'BlacklistController');
    Route::post('ajax-blacklist', 'BlacklistController@show_svs')->name('svs_blacklist');

    Route::get('clear-cache/{cache_option?}/{slug_cache?}', 'CacheController@_clearCache');

    Route::get('run-bot', 'ScraperController@_index')->name('run_bot_keywords');

    Route::post('other-get-info', 'ScraperController@_getOtherInfo');
    Route::post('track-control', 'ScraperController@_trackControl');
    Route::post('track-bing', 'ScraperController@_bingPost')->name('bing_scraper');
    Route::post('track-google', 'ScraperController@_googleScraper')->name('google_scraper');
    Route::post('track-amz', 'ScraperController@_amzScraper')->name('amz_scraper');

    Route::get('bot-multi', 'ScraperController@_vBotMulti')->name('bot_multi');
    Route::post('get-keyword', 'ScraperController@_getKeyword');
    Route::post('add-2-sitemap', 'ScraperController@_add2Sitemap');

    Route::get('file-manager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('file-manager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');

});

Route::get('/{slug?}', 'Keyword\KeywordViewController@_viewKeyword')->name('v_keyword');

/*Migration DB
php artisan migrate --path=/database/migrations/2019_08_28_152107_create_categories_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_150242_create_spam_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_152854_create_results_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_151618_create_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_131221_create_coupons_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_135230_create_keys_related.php
db.categories.getIndexes();
*/

app/Http/Controllers/Store/SyncsController.php
<?php

namespace App\Http\Controllers\Store;

use App\Categories;
use App\Coupons;
use App\Http\Controllers\EsController;
use App\Stores;
use App\SyncsModel;
use Carbon\Carbon;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;
use MongoDB\BSON\ObjectId;

class SyncsController extends Controller
{
    private $api_couponupto = 'https://www.couponupto.com/api/v1-get-info';
    //private $api_couponupto = 'http://127.0.0.1:8001/api/v1-get-info';
    private $secret = 'howtogetinfo_lol';
    private $cache_time = 5;
    private $client_http, $es;

    public function __construct()
    {
        $this->middleware(['auth']);
        $this->client_http = new Client();
        $this->es = new EsController();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        //
        return view('cpanel.syncs.index_table');
    }

    protected function _SyncOne(Request $request)
    {
        if ($request->id) {
            $id = trim($request->id);
            $from = trim($request->from_collection) ?? false;
            if ($from == 'store') {
                $info_store = Stores::where('_id', $id)->first()->toArray();
                if ($info_store) {
                    $params = [
                        'hash_md5' => md5(json_encode($info_store['_id']) . $this->secret),
                        'datum' => $info_store,
                        'type' => 'one-store'
                    ];
                } else {
                    $params = 'store id not found:' . $id;
                }
            } else {
                $info_sync = SyncsModel::where('_id', $id)->first()->toArray();
                if ($info_sync) {
                    $params = [
                        'hash_md5' => md5(json_encode($info_sync['_id']) . $this->secret),
                        'datum' => $info_sync,
                        'type' => 'one-sync'
                    ];
                } else {
                    $params = 'sync id not found:' . $id;
                }
            }
            if (!is_array($params)) {
                return response()->json(['code' => 98, 'msg' => $params]);
            }
            /*Send Post API*/
            $get_info = $this->client_http->request('POST', $this->api_couponupto, [
                'form_params' => $params
            ]);
            $body = json_decode((string)$get_info->getBody());
            if ($body->code == 1) {
                $res_data = $body->res;
                $coupons = $res_data->coupons;
                unset($res_data->coupon_added);
                unset($res_data->coupons);
                unset($res_data->rich_content);
                unset($res_data->store_aff);
                $orNewStore = Stores::updateOrCreate(
                    ['slug_store' => $res_data->slug_store]
                    , (array)$res_data
                );
                // $this->es->_findAndUpdate('stores', '_doc', $orNewStore, true);
                // dd($coupons);
                foreach ($coupons as $index_2 => $coupon) {
                    if (isset($coupon->hash_r) && $coupon->hash_r != null) {
                    $change_info = changeInfoCoupon($coupon, $res_data);
                    $coupon->coupon_name = $change_info['title'];
                    $coupon->coupon_excerpt = $change_info['desc'];
                    Coupons::firstOrCreate(
                        ['coupon_slug' => $coupon->coupon_slug],
                        (array)$coupon
                    );  
                    }else{
                        $coupon->hash_r = md5(json_encode($coupon->_id) . $this->secret);
                        $change_info = changeInfoCoupon($coupon, $res_data);
                        $coupon->coupon_name = $change_info['title'];
                        $coupon->coupon_excerpt = $change_info['desc'];
                        try {
                            Coupons::firstOrCreate(
                                ['coupon_slug' => $coupon->coupon_slug],
                                (array)$coupon
                            );
                        } catch (\Exception $exception) {
                        }
                    }
                }
                return response()->json([$res_data->store_name, count($coupons) . ' coupons']);
            } else {
                return response()->json($body);
            }
        } else {
            return response()->json('Params Error');
        }
    }

    protected function _gstartSync(Request $request)
    {
        return view('cpanel.syncs.sync_start');
    }

    protected function _startSync(Request $request)
    {
        $limit = 50;
        $tracked = 0;
        $active_stt = 0;
        $store_aff = false;
        if ($request->store_aff == true) {
            $store_aff = true;
        }
        if ($request->active_stt == true) {
            $active_stt = 1;
        }
        $total = SyncsModel::where('tracked', $tracked)->count();
        $total_page = intval($total / $limit);
        for ($i = 0; $i <= $total_page; $i++) {
            $skip = $i * $limit;
            $datum = collect(SyncsModel::select('connect_id', 'type_source')
                ->where('tracked', $tracked)
                ->orderBy('updated_at', 'asc')
                ->skip($skip)
                ->take($limit)->get());
            //print_r("===================Starting Page:" . $i . "/" . $total_page . PHP_EOL);
            $ids_datum = [];
            $group_by_source = $datum->groupBy('type_source')->toArray();
            if (count($group_by_source) == 0) {
                dd("===============All DONE=================");
            }
            foreach ($group_by_source as $key => $items) {
                $connect_ids = [];
                $ids = [];
                foreach ($items as $item) {
                    $connect_ids[] = trim($item['connect_id']);
                    $ids[] = trim($item['_id']);
                }
                $group_by_source[$key] = ['connect_ids' => $connect_ids, 'ids' => $ids];
            }
            $rand_key = rand(0, 9999);
            $params = [
                'hash_md5' => md5($rand_key . $this->secret),
                'datum' => $group_by_source,
                'rand_id' => $rand_key
            ];
            $get_info = $this->client_http->request('POST', $this->api_couponupto, [
                'form_params' => $params
            ]);
            $body = json_decode((string)$get_info->getBody());
            if ($body->code == 1) {
                $res_data = $body->res;
                $results_msg = [];
                foreach ($res_data as $key => $stores) {
                    foreach ($stores as $index => $store) {
                        if (property_exists($store, 'coupons')) {
                            $coupons = $store->coupons;
                            unset($store->coupons);
                            unset($store->rich_content);
                            if (!$store_aff) {
                                unset($store->store_aff);
                            }
                            $store->connect_id = $store->_id;
                            $store->active_stt = $active_stt;
                            if (property_exists($store, 'slug_store')) {
                                array_push($ids_datum, $store->connect_id);
                                $orNewStore = Stores::updateOrCreate(
                                    ['slug_store' => $store->slug_store]
                                    , (array)$store
                                );
                                // $this->es->_findAndUpdate('stores', '_doc', $orNewStore, true);
                                $coupons = collect($coupons);
                                $pluck_coupon_slug = $coupons->pluck('coupon_slug')->all();
                                $pluck_exits = Coupons::whereIn('coupon_slug', $pluck_coupon_slug)->pluck('coupon_slug')->toArray();
                                $diff_result = array_diff($pluck_coupon_slug, $pluck_exits);
                                foreach ($coupons->toArray() as $index_2 => $coupon) {
                                    // dd($coupon);
                                    if (isset($coupon->hash_r) && $coupon->hash_r != null) {
                                        if (in_array($coupon->coupon_slug, $diff_result)) {
                                            $change_info = changeInfoCoupon((object)$coupon, (object)$store);
                                            $coupon->coupon_name = $change_info['title'];
                                            $coupon->coupon_excerpt = $change_info['desc'];
                                            try {
                                                Coupons::insert((array)$coupon);
                                            } catch (\Exception $exception) {
                                            }
                                        }
                                    } else {
                                        $coupon->hash_r = md5(json_encode($coupon->_id) . $this->secret);
                                        if (in_array($coupon->coupon_slug, $diff_result)) {
                                            $change_info = changeInfoCoupon((object)$coupon, (object)$store);
                                            $coupon->coupon_name = $change_info['title'];
                                            $coupon->coupon_excerpt = $change_info['desc'];
                                            try {
                                                Coupons::insert((array)$coupon);
                                            } catch (\Exception $exception) {
                                            }
                                        }

resources/views/cpanel/syncs/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Add New Syncs</h1>
@stop

@section('content')
    <div class="col-md-8">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            {!! Form::open(['route' => 'cpanel.syncs.store']) !!}
            {!! Form::token(); !!}
            <div class="box-body">
                <div class="form-group">
                    <label for="store_name">Type Source</label>
                    <select class="form-control" name="type_source" id="type_source">
                        <option value="coupons" selected>/Coupons</option>
                        <option value="deals">/Deals</option>
                        <option value="promos">/Promos</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Of Category</label>
                    <select multiple="" class="form-control" name="store_cat[]">
                        @foreach($categories as $category)
                            <option value="{{$category['slug']}}">{{$category['name']}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>List Ids Connect</label>
                    <textarea class="form-control" id="list_ids" name="list_ids" rows="5"
                              placeholder="Per Id per row..."></textarea>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header with-border">

            </div>
        </div>
    </div>
@stop

resources/views/cpanel/syncs/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Edit Sync: {{$edit['store_name']}}</h1>
@stop

@section('content')
    <div class="col-md-8">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{ route('cpanel.syncs.update',['id' =>  $edit['_id'] ]) }}" method="post">
                {!! Form::token(); !!}
                <div class="box-body">
                    <div class="form-group">
                        <label for="store_name">Connect ID</label>
                        <input type="text" class="form-control" name="connect_id" id="connect_id"
                               value="{{$edit['connect_id']}}">
                    </div>
                    <div class="form-group">
                        <label for="store_name">Type Source</label>
                        <select class="form-control" name="type_source" id="type_source">
                            <option value="coupons" @if ($edit['type_source'] == 'coupons')selected @endif>/Coupons
                            </option>
                            <option value="deals" @if ($edit['type_source'] == 'deals')selected @endif>/Deals</option>
                            <option value="promos" @if ($edit['type_source'] == 'promos')selected @endif>/Promos</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Of Category</label>
                        <select multiple="" class="form-control" name="store_cat[]">
                            @foreach($categories as $category)
                                @if(in_array($category['category_slug'], explode(",",$edit['store_cat'])))
                                    <option value="{{$category['slug']}}" selected>
                                        {{$category['name']}}
                                    </option>';
                                @else
                                    <option value="{{$category['slug']}}">
                                        {{$category['name']}}
                                    </option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header with-border">

            </div>
        </div>
    </div>

@stop
@section('js')
    <script src="{{asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script>
    <script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
    <script>
        var domain = "/c-panel/file-manager";
        $('#lfm').filemanager('image', {prefix: domain});
        var options = {
            filebrowserImageBrowseUrl: '/c-panel/file-manager?type=Images',
            filebrowserImageUploadUrl: '/c-panel/file-manager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/c-panel/file-manager?type=Files',
            filebrowserUploadUrl: '/c-panel/file-manager/upload?type=Files&_token='
        };

        $(document).ready(function () {
            CKEDITOR.replace('rich_content', options);
        });
    </script>
@endsection

resources/views/cpanel/syncs/index_table.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1><i class="fa fa-shopping-cart"></i> List Sync</h1>
    <ol class="breadcrumb">
        <li><a href="/c-panel"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#" class="active">Stores</a></li>
    </ol>
    <br/>
    <a class="btn btn-success" href="{{route('cpanel.syncs.create')}}">
        <i class=" fa fa-plus-circle"></i>
        Create New Sync
    </a>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
@stop

@section('content')
    @isset ($msg)
        <div class="alert alert-success">
            <p>{{ $msg }}</p>
        </div>
    @endisset
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Store Info</th>
                <th>Sync Config</th>
                <th>Add/Update Date</th>
                <th>-</th>
            </tr>
            </thead>
        </table>
    </div>
@stop
@section('js')
    <script src="{{asset('/js/jquery.lazyload.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#data-table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "{{ route('cpanel.all_sync') }}",
                    "dataType": "json",
                    "type": "POST",
                    "data": {_token: "{{csrf_token()}}"}
                },
                "columns": [
                    {"data": "store_info"},
                    {"data": "connect_id"},
                    {"data": "created_at"},
                    {"data": "options"}
                ],
                "drawCallback": function () {
                    $("img.lazyload").lazyload();
                }
            });
            $("img.lazyload").lazyload({
                threshold: 200
            });
        });

        $(document).on('click', 'a.jquery-postback', function (e) {
            e.preventDefault(); // does not go through with the link.

            var $this = $(this);
            var name_store = $(this).data('store');
            var id_store = $(this).data('id-store');
            console.log($(this).data('store'));
            $.post({
                type: $this.data('method'),
                url: $this.attr('href')
            }).done(function (data) {
                alert('Success remove: ' + name_store);
                $("#" + id_store).hide();
            });
        });
    </script>
@endsection

resources/views/cpanel/syncs/sync_start.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Start Sync</h1>
@stop

@section('content')
    <div class="col-md-8">
        <p class="text-center">
            <label class="checkbox-inline"><input type="checkbox" value="store_aff">Sync Link Aff</label>
            <label class="checkbox-inline"><input type="checkbox" value="active_stt">Active Stores</label>
        </p>
        <div class="form-group">
            <input type="button" class="btn btn-block btn-primary" id="start-sync" value="Start Sync"/>
        </div>
        <div class="progress" style="display: none" id="running_stt">
            <div class="progress-bar progress-bar-striped active" role="progressbar"
                 aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
                I'm Running Man, Please wait for moment...
            </div>
        </div>
        <div class="box box-primary">
            <ol id="result_msg" reversed></ol>
        </div>
    </div>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            function start(data_send) {
                $("#running_stt").show();
                $.post({
                    type: 'POST',
                    url: '/c-panel/sync-start',
                    data: data_send,
                }).done(function (data) {
                    if (typeof data.code === "undefined" || data.code !== 0) {
                        $("#result_msg").prepend("<li>" + data + "</li>");
                        start(data_send);
                    } else {
                        $("#running_stt").hide();
                        $("#result_msg").prepend("<li>" + JSON.stringify(data) + "</li>");
                    }
                });
            }

            let data_send = {};
            $("input[type=checkbox]").change(function () {
                if ($(this).is(':checked')) {
                    data_send[$(this).val()] = true;
                } else {
                    delete data_send[$(this).val()];
                }
                console.log(data_send);
            });
            $("#start-sync").click(function () {
                start(data_send);
            });
        });
    </script>
@endsection