routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@_index')->name('home');

Route::get('/search', 'Keyword\KeywordViewController@_searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@_autocomplete')->name('search_autocomplete');
Route::post('/related-keyword', 'Keyword\KeywordViewController@_relatedKeyword');
// add route post_faq
Route::post('/faq/{id_kw}/{id_q}', 'Keyword\KeywordViewController@_postFAQs')->name('post_faq');

Route::get('/more-info/{domain?}', 'Keyword\KeywordViewController@_moreOffers');

Route::get('/v-result/{result_id?}', 'Keyword\KeywordViewController@_outLink')->name('result_out');

Route::get('/blog/{slug?}', 'Posts\PostViewController@_blog')->name('blog');
Route::post('/saving-email', 'HomeController@_savingEmail')->name('saveEmail');

Route::get('/sitemap-job/xml/{file_name}', 'SiteMapController@_sitemapDynamic');

Route::get('/store/{slug}','Store\StoreViewController@stores')->name('stores');

Route::get('/clear-cache-ar', function () {
    $exitCode = \Illuminate\Support\Facades\Artisan::call('config:clear');
    $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
    return 'DONE'; //Return anything
});
Auth::routes();
Route::group(['prefix' => 'c-panel', 'as' => 'cpanel.'], function () {
    Route::get('/', 'DashboardController@index')->name('home-dashboard');
    Route::get('/clear-cache', function () {
        $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
        return view('cpanel.cache_clear');
    });

    Route::resource('tags', 'Tags\CmsTagsController');
    Route::post('tags/{id}', 'Tags\CmsTagsController@update');
    Route::post('tags-table', 'Tags\CmsTagsController@index')->name('tags.table');

    Route::resource('tags_kw', 'Tags\TagsKWController');
    Route::post('tags_kw/{id}', 'Tags\TagsKWController@update');
    Route::post('tags_kw-effect', 'Tags\TagsKWController@_checkEffect');
    Route::post('tags_kw-table', 'Tags\TagsKWController@index')->name('tags_kw.table');

    Route::resource('emails', 'EmailController');
    Route::get('email-send', 'EmailController@_sendEmail')->name('email.get-send');
    Route::post('email-send', 'EmailController@_sendEmail')->name('email.post-send');
    Route::post('emails-table', 'EmailController@show_svs')->name('emails.show_table');

    Route::resource('categories', 'CategoriesController');
    Route::post('ajax-categories', 'CategoriesController@show_svs')->name('svs_categories');

    Route::resource('config-site', 'CmsConfigController');
 
    Route::resource('keywords', 'Keyword\CmsKeysController');
    Route::post('keywords/{id}', 'Keyword\CmsKeysController@update');
    Route::get('add-kw-excel', 'Keyword\CmsKeysController@_vAddExcel');
    Route::post('add-kw-excel', 'Keyword\CmsKeysController@_addExcel')->name('add_kw_excel');
    Route::post('add-kw-txt', 'Keyword\CmsKeysController@_addTXT');

    Route::get('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('get-remove-keyword');
    Route::post('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('post-remove-keyword');
    Route::post('ajax-keyword-black', 'BlacklistController@show_svs_kw')->name('svs_keyword_black');

    Route::post('ajax-keywords', 'Keyword\CmsKeysController@show_svs')->name('svs_keywords');
    Route::get('add-connect', 'Keyword\CmsKeysController@_vAddCUT');
    Route::post('add-connect', 'Keyword\CmsKeysController@_pAddCUT')->name('add_connect');
    Route::get('add-connect-store', 'Keyword\CmsKeysController@_connectToStore');
    Route::post('add-connect-store', 'Keyword\CmsKeysController@_pConnectToStore')->name('add_connect_store');

    Route::post('/daterange/kw_crawled', 'Keyword\CmsKeysController@kw_crawled')->name('daterange.kw_crawled');

    Route::resource('posts', 'Posts\CmsPostController');
    Route::post('posts/{id}', 'Posts\CmsPostController@update');
    Route::post('ajax-posts', 'Posts\CmsPostController@show_svs')->name('svs_posts');

    

    
    Route::get('add-excel', 'Store\CmsStoreController@add')->name('stores.add_excel');
    Route::post('add-excel/stores', 'Store\CmsStoreController@_addTXT')->name('stores.add_excel_post');
    Route::get('export-excel', 'Store\CmsStoreController@export')->name('stores.export_excel');
    Route::post('export-excel', 'Store\CmsStoreController@_pexportAllURL')->name('stores.p_export');
    Route::post('store-remove/{id}', 'Store\CmsStoreController@destroy')->name('stores.destroy');
    Route::resource('stores', 'Store\CmsStoreController');
    Route::post('stores/{id}', 'Store\CmsStoreController@update');
    Route::post('ajax-stores', 'Store\CmsStoreController@svs_store')->name('all_stores');
    // route update stt
    Route::post('/update-store-stt','Store\CmsStoreController@_updateStt');


    Route::resource('syncs', 'Store\SyncsController');
    Route::post('syncs/{id}', 'Store\SyncsController@update');
    Route::post('all-sync','Store\SyncsController@stores_svs')->name('all_sync');

    Route::post('/sync-one','Store\SyncsController@_SyncOne');
    Route::post('/sync-start','Store\SyncsController@_startSync');
    Route::get('/sync-start','Store\SyncsController@_gstartSync');

    Route::resource('blacklist', 'BlacklistController');
    Route::post('ajax-blacklist', 'BlacklistController@show_svs')->name('svs_blacklist');

    Route::get('clear-cache/{cache_option?}/{slug_cache?}', 'CacheController@_clearCache');

    Route::get('run-bot', 'ScraperController@_index')->name('run_bot_keywords');

    Route::post('other-get-info', 'ScraperController@_getOtherInfo');
    Route::post('track-control', 'ScraperController@_trackControl');
    Route::post('track-bing', 'ScraperController@_bingPost')->name('bing_scraper');
    Route::post('track-google', 'ScraperController@_googleScraper')->name('google_scraper');
    Route::post('track-amz', 'ScraperController@_amzScraper')->name('amz_scraper');

    Route::get('bot-multi', 'ScraperController@_vBotMulti')->name('bot_multi');
    Route::post('get-keyword', 'ScraperController@_getKeyword');
    Route::post('add-2-sitemap', 'ScraperController@_add2Sitemap');

    Route::get('file-manager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('file-manager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');

});

Route::get('/{slug?}', 'Keyword\KeywordViewController@_viewKeyword')->name('v_keyword');

/*Migration DB
php artisan migrate --path=/database/migrations/2019_08_28_152107_create_categories_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_150242_create_spam_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_152854_create_results_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_151618_create_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_131221_create_coupons_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_135230_create_keys_related.php
db.categories.getIndexes();
*/

app/Http/Controllers/Tags/TagsKWController.php
<?php

namespace App\Http\Controllers\Tags;

use App\Http\Controllers\Controller;
use App\Jobs\ProcessMarkTags;
use App\Keywords;
use App\TagsKW;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class TagsKWController extends Controller
{
    private $cache_short = 5;
    private $cache_hourly = 60;
    private $cache_monthly = 60 * 24 * 30;

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $columns = array(
                0 => 'tag_type',
                1 => 'for_keyword',
                2 => 'created_at',
                3 => 'options',
            );
            try {
                $limit = intval($request->input('length'));
                $start = $request->input('start');
                $order = $columns[$request->input('order.0.column')];
                $dir = $request->input('order.0.dir');
                $hash = md5($limit . $start . $order . $dir);

                $totalData = Cache::remember('totalData' . $hash, $this->cache_short, function () {
                    return TagsKW::count();
                });

                $totalFiltered = $totalData;

                if (empty($request->input('search.value'))) {
                    $posts = Cache::remember('tags_kw' . $hash, $this->cache_short, function () use ($start, $limit, $order, $dir) {
                        return TagsKW::offset(intval($start))
                            ->take($limit)
                            ->orderBy($order, $dir)
                            ->get();
                    });
                } else {
                    $search = $request->input('search.value');
                    $hash = md5($limit . $start . $order . $dir . $search . "cat_list");
                    $posts = Cache::remember('tags_kw' . $hash, $this->cache_short, function () use ($search, $start, $limit, $order, $dir) {
                        return TagsKW::where('for_keyword', 'LIKE', "%{$search}%")
                            ->offset(intval($start))
                            ->take($limit)
                            ->orderBy($order, $dir)
                            ->get();
                    });
                    $totalFiltered = Cache::remember('totalFiltered' . $hash, $this->cache_short, function () use ($search) {
                        return TagsKW::where('for_keyword', 'LIKE', "%{$search}%")
                            ->count();
                    });
                }
                $data = array();
                if (!empty($posts)) {
                    foreach ($posts as $post) {
                        $nestedData['tag_type'] = $post['tag_type'] . '<br/>' . $post['tag_name'];
                        $nestedData['for_keyword'] = $post['for_keyword'] . '<small><br/>Id Tag: ' . $post['_id'] . '<br/>Effect: ' . $post['effected'] . '</small>';
                        $nestedData['created_at'] = 'Created at:' . Carbon::parse($post['created_at'])->format('d-m-Y H:m:s') . '<br/>Updated at:' . Carbon::parse($post['updated_at'])->format('d-m-Y H:m:s') . '<br/>';
                        $nestedData['options'] = '<a title="Edit: ' . $post['tag_name'] . '" href="' . route('cpanel.tags_kw.edit', ['id' => $post['_id']]) . '"><span class="label label-primary"><i class="fa fa-edit"></i></span></a>
                        <a title="Remove: ' . $post['tag_name'] . '" href="' . route('cpanel.tags_kw.destroy', $post['_id']) . '" data-id="' . $post['_id'] . '" data-name="' . $post['tag_name'] . '" data-method="delete" class="jquery-postback"><span class="label label-danger"><i class="fa fa-window-close"></i></span></a>';
                        $nestedData['_id'] = $post['_id'];
                        $data[] = $nestedData;
                    }
                }

                $json_data = array(
                    "draw" => intval($request->input('draw')),
                    "recordsTotal" => intval($totalData),
                    "recordsFiltered" => intval($totalFiltered),
                    "data" => $data,
                    "hash" => $hash,
                );
                echo json_encode($json_data);
            } catch (\Exception $e) {
                dd($e);
            }
        } else {
            return view('cpanel.tags_kw.index_table');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('cpanel.tags_kw.add');
    }

    protected function _checkEffect(Request $request)
    {
        if ($request->for_keyword) {
            $keyword_slug = str_replace('*', '%', trim(strtolower($request->for_keyword)));
            $keyword_slug = str_replace(' ', '-', $keyword_slug);
            $effect = Cache::remember('effect' . $keyword_slug, $this->cache_short, function () use ($keyword_slug) {
                return Keywords::where('keyword_slug', 'LIKE', $keyword_slug)->count();
            });
            $request->session()->flash('effect' . slugify($request->for_keyword), $effect);
            return $effect;
        } else {
            return 0;
        }
    }

    private function _keywordTrust($keyword_slug)
    {
        $filter_str = preg_replace('/[^A-Za-z0-9\-]/', '', $keyword_slug);
        $filter_str = str_replace('-', '', $filter_str);
        if (strlen($filter_str) == 3) {
            return trim(str_replace('*', ' *', $keyword_slug));
        } elseif (strlen($filter_str) < 3) {
            return false;
        } else {
            return trim($keyword_slug);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        if ($request->tag_type == '') {
            return back(302)->withErrors(['Tag Type Null']);
        } else {
            try {
                $hash_r = md5(trim(strtolower($request->tag_type . $request->tag_name)));
                $kw_trust = $this->_keywordTrust($request->for_keyword);
                if ($kw_trust === false) {
                    return back(302)->withErrors(['Keyword slug illegal']);
                }
                $exits = TagsKW::where('hash_r', $hash_r)->count();
                if ($exits > 0) {
                    return back(302)->withErrors(['Tag Name Exits']);
                }
                $new_tag = new TagsKW();
                $new_tag->tag_name = trim($request->tag_name);
                $new_tag->hash_r = $hash_r;
                $new_tag->tag_type = trim($request->tag_type);
                $new_tag->for_keyword = $kw_trust;
                $new_tag->foreign_id = trim($request->foreign_id);
                $new_tag->foreign_url = trim($request->foreign_url);
                $new_tag->rel = trim($request->rel);
                if (session('effect' . slugify($request->for_keyword))) {
                    $new_tag->effected = session('effect' . slugify($request->for_keyword));
                }
                $new_tag->save();
                /*Send Job Queue Mark Tag*/
                $job_addTag = (new ProcessMarkTags($new_tag));
                $this->dispatch($job_addTag);
                return redirect(route('cpanel.tags_kw.index'), 302);
            } catch (\Exception $e) {
                dd($e);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        if ($id) {
            $editor = TagsKW::find($id);
            if ($editor) {
                return view('cpanel.tags_kw.edit', compact(['editor']));
            } else {
                return back(302)->with('ID not found');
            }
        } else {
            return back(302)->with('Id not found');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        if ($id) {
            $update_tag = TagsKW::find($id);
            $update_tag->for_keyword = trim($request->for_keyword);
            $update_tag->tag_type = trim($request->tag_type);
            $update_tag->foreign_id = trim($request->foreign_id);
            $update_tag->foreign_url = trim($request->foreign_url);
            $update_tag->rel = trim($request->rel);
            if (session('effect' . slugify($request->for_keyword))) {
                $update_tag->effected = session('effect' . slugify($request->for_keyword));
            }
            $update_tag->save();
            /*Send Job Queue Mark Tag*/
            $job_addTag = (new ProcessMarkTags($update_tag));
            $this->dispatch($job_addTag);
            return back(302)->with('Updated success');
        } else {
            return back(302)->with('Update fail');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        if ($id) {
            TagsKW::where('_id', $id)->delete();
            return response()->json(['code' => 1, 'msg' => 'Deleted Success']);
        } else {
            return response()->json(['code' => 99, 'msg' => 'Fail']);
        }
    }
}

resources/views/cpanel/tags_kw/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Add New Tags</h1>
@stop

@section('content')
    @if($errors->any())
        <p class="alert alert-error">{{$errors->first()}}</p>
    @endif
    <div class="col-12">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            {!! Form::open(['route' => 'cpanel.tags_kw.store']) !!}
            {!! Form::token(); !!}
            <div class="box-body">
                <div class="form-group">
                    <label for="tag_type">Tag Type</label>
                    <select class="form-control" id="tag_type" name="tag_type">
                        <option value="" selected>--Select--</option>
                        <option value="internal_id">Store Internal By ID</option>
                        <option value="external_url">External URL (Replica Top 1 Info)</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="tag_name">Tag Name</label>
                    <input type="text" class="form-control" name="tag_name" id="tag_name"
                           placeholder="include tag name"/>
                </div>
                <div class="form-group">
                    <label for="for_keyword">Will Add For Keyword: (keyword_slug, *keyword_slug,
                        *keyword_slug*,keyword_slug*)</label>
                    <input type="text" class="form-control" name="for_keyword" id="for_keyword"/>
                </div>
                <div class="form-group">
                    <label for="foreign_id">Store ID</label>
                    <input type="text" class="form-control" name="foreign_id" id="foreign_id"
                           placeholder="Include if tag type: Store Internal"/>
                </div>
                <div class="form-group">
                    <label for="foreign_url">External URL</label>
                    <input type="text" class="form-control" name="foreign_url" id="foreign_url"
                           placeholder="Include if tag type: External URL"/>
                </div>
                <div class="form-group">
                    <label for="rel">Referral</label>
                    <select class="form-control" id="rel" name="rel">
                        <option value="nofollow" selected>No Follow</option>
                        <option value="dofollow">Do Follow</option>
                        <option value="nofollow noreferrer">Will Show Direct Source</option>
                    </select>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('js')
    <script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('snippet');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('input[name="_token"]').val()
                }
            });
            $('#for_keyword').blur(function () {
                if ($('#for_keyword').val().length < 4) {
                    alert('Keyword slug:' + $('#for_keyword').val() + ' illegal');
                    $(':button[type="submit"]').prop('disabled', true);
                } else {
                    $.post('/c-panel/tags_kw-effect', {
                        _token: $('input[name="_token"]').val(),
                        for_keyword: $('#for_keyword').val()
                    }).done(function (data) {
                        if (data === 0) {
                            $(':button[type="submit"]').prop('disabled', true);
                            alert('Keyword will effect to ' + data + ' keywords');
                        } else {
                            $(':button[type="submit"]').prop('disabled', false);
                            alert('Keyword will effect to ' + data + ' keywords');
                        }

                    });
                }
            });
        });
    </script>
@endsection

resources/views/cpanel/tags_kw/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Edit Tag: {{$editor['tag_name']}}</h1>
@stop
@section('content')
    @if($errors->any())
        <p class="alert alert-error">{{$errors->first()}}</p>
    @endif
    <div class="col-12">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{ route('cpanel.tags_kw.update',['id' =>  $editor['_id'] ]) }}" method="post">
                {!! Form::token(); !!}
                <div class="box-body">
                    <div class="form-group">
                        <label for="tag_type">Tag Type</label>
                        <select class="form-control" id="tag_type" name="tag_type">
                            <option value="">--Select--</option>
                            <option value="internal_id" @if($editor['tag_type'] == 'internal_id') selected @endif>Store Internal By ID</option>
                            <option value="external_url" @if($editor['tag_type'] == 'external_url') selected @endif>External URL (Replica Top 1 Info)</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tag_name">Tag Name</label>
                        <input type="text" class="form-control" name="tag_name" id="tag_name"
                               value="{{$editor['tag_name']}}"
                               placeholder="include tag name" disabled/>
                    </div>
                    <div class="form-group">
                        <label for="for_keyword">Keyword Slug: (keyword_slug, *keyword_slug,
                            *keyword_slug*,keyword_slug*)</label>
                        <input type="text" class="form-control" name="for_keyword" id="for_keyword"
                               value="{{$editor['for_keyword']}}"/>
                    </div>
                    <div class="form-group">
                        <label for="for_id">Store ID</label>
                        <input type="text" class="form-control" name="foreign_id" id="foreign_id"
                               value="{{$editor['foreign_id']}}"
                               placeholder="Include if tag type: Store Inline By ID"/>
                    </div>
                    <div class="form-group">
                        <label for="for_url">External URL</label>
                        <input type="text" class="form-control" name="foreign_url" id="foreign_url"
                               value="{{$editor['foreign_url']}}"
                               placeholder="Include if tag type: By URL"/>
                    </div>
                    <div class="form-group">
                        <label for="rel">Referral</label>
                        <select class="form-control" id="rel" name="rel">
                            <option value="nofollow" @if($editor['rel'] == 'nofollow') selected @endif>No Follow</option>
                            <option value="dofollow" @if($editor['rel'] == 'dofollow') selected @endif>Do Follow</option>
                            <option value="nofollow noreferrer" @if($editor['rel'] == 'nofollow noreferrer') selected @endif>Will Show Direct Source</option>
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
@stop
@section('js')
    <script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('snippet');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('input[name="_token"]').val()
                }
            });
            $('#for_keyword').blur(function () {
                if ($('#for_keyword').val().length < 4) {
                    alert('Keyword slug:' + $('#for_keyword').val() + ' illegal');
                    $(':button[type="submit"]').prop('disabled', true);
                } else {
                    $.post('/c-panel/tags_kw-effect', {
                        _token: $('input[name="_token"]').val(),
                        for_keyword: $('#for_keyword').val()
                    }).done(function (data) {
                        if (data === 0) {
                            $(':button[type="submit"]').prop('disabled', true);
                            alert('Keyword will effect to ' + data + ' keywords');
                        } else {
                            $(':button[type="submit"]').prop('disabled', false);
                            alert('Keyword will effect to ' + data + ' keywords');
                        }

                    });
                }
            });
        });
    </script>
@endsection

resources/views/cpanel/tags_kw/index_table.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1><i class="fa fa-tags"></i> List Tags For Keyword</h1>
    <ol class="breadcrumb">
        <li><a href="/c-panel"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#" class="active">Tags</a></li>
    </ol>
    <br/>
    <a class="btn btn-success" href="{{route('cpanel.tags_kw.create')}}">
        <i class=" fa fa-plus-circle"></i>
        Create New Tags
    </a>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
@stop

@section('content')
    @isset ($msg)
        <div class="alert alert-success">
            <p>{{ $msg }}</p>
        </div>
    @endisset
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Tag Type</th>
                <th>Effect Keyword</th>
                <th>Created At</th>
                <th>-</th>
            </tr>
            </thead>
        </table>
    </div>
@endsection
@section('js')
    <script src="{{asset('/js/jquery.lazyload.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#data-table').DataTable({
                "processing": true,
                "serverSide": true,
                "rowId": '_id',
                "ajax": {
                    "url": "{{ route('cpanel.tags_kw.table') }}",
                    "dataType": "json",
                    "type": "POST",
                    "data": {_token: "{{csrf_token()}}"}
                },
                "columns": [
                    {"data": "tag_type"},
                    {"data": "for_keyword"},
                    {"data": "created_at"},
                    {"data": "options"}
                ]
            });
        });
        $(document).on('click', 'a.jquery-postback', function (e) {
            e.preventDefault(); // does not go through with the link.
            let id = $(this).data('id'), name = $(this).data('id');
            $this = $(this);
            $.post({
                type: $this.data('method'),
                url: $this.attr('href')
            }).done(function (data) {
                alert('Success remove: ' + name);
                $("#" + id).hide();
            });
        });
    </script>
@endsection