routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@_index')->name('home');

Route::get('/search', 'Keyword\KeywordViewController@_searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@_autocomplete')->name('search_autocomplete');
Route::post('/related-keyword', 'Keyword\KeywordViewController@_relatedKeyword');
// add route post_faq
Route::post('/faq/{id_kw}/{id_q}', 'Keyword\KeywordViewController@_postFAQs')->name('post_faq');

Route::get('/more-info/{domain?}', 'Keyword\KeywordViewController@_moreOffers');

Route::get('/v-result/{result_id?}', 'Keyword\KeywordViewController@_outLink')->name('result_out');

Route::get('/blog/{slug?}', 'Posts\PostViewController@_blog')->name('blog');
Route::post('/saving-email', 'HomeController@_savingEmail')->name('saveEmail');

Route::get('/sitemap-job/xml/{file_name}', 'SiteMapController@_sitemapDynamic');

Route::get('/store/{slug}','Store\StoreViewController@stores')->name('stores');

Route::get('/clear-cache-ar', function () {
    $exitCode = \Illuminate\Support\Facades\Artisan::call('config:clear');
    $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
    return 'DONE'; //Return anything
});
Auth::routes();
Route::group(['prefix' => 'c-panel', 'as' => 'cpanel.'], function () {
    Route::get('/', 'DashboardController@index')->name('home-dashboard');
    Route::get('/clear-cache', function () {
        $exitCode = \Illuminate\Support\Facades\Artisan::call('cache:clear');
        return view('cpanel.cache_clear');
    });

    Route::resource('tags', 'Tags\CmsTagsController');
    Route::post('tags/{id}', 'Tags\CmsTagsController@update');
    Route::post('tags-table', 'Tags\CmsTagsController@index')->name('tags.table');

    Route::resource('tags_kw', 'Tags\TagsKWController');
    Route::post('tags_kw/{id}', 'Tags\TagsKWController@update');
    Route::post('tags_kw-effect', 'Tags\TagsKWController@_checkEffect');
    Route::post('tags_kw-table', 'Tags\TagsKWController@index')->name('tags_kw.table');

    Route::resource('emails', 'EmailController');
    Route::get('email-send', 'EmailController@_sendEmail')->name('email.get-send');
    Route::post('email-send', 'EmailController@_sendEmail')->name('email.post-send');
    Route::post('emails-table', 'EmailController@show_svs')->name('emails.show_table');

    Route::resource('categories', 'CategoriesController');
    Route::post('ajax-categories', 'CategoriesController@show_svs')->name('svs_categories');

    Route::resource('config-site', 'CmsConfigController');
 
    Route::resource('keywords', 'Keyword\CmsKeysController');
    Route::post('keywords/{id}', 'Keyword\CmsKeysController@update');
    Route::get('add-kw-excel', 'Keyword\CmsKeysController@_vAddExcel');
    Route::post('add-kw-excel', 'Keyword\CmsKeysController@_addExcel')->name('add_kw_excel');
    Route::post('add-kw-txt', 'Keyword\CmsKeysController@_addTXT');

    Route::get('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('get-remove-keyword');
    Route::post('keyword-remove', 'Keyword\CmsKeysController@_removeKw')->name('post-remove-keyword');
    Route::post('ajax-keyword-black', 'BlacklistController@show_svs_kw')->name('svs_keyword_black');

    Route::post('ajax-keywords', 'Keyword\CmsKeysController@show_svs')->name('svs_keywords');
    Route::get('add-connect', 'Keyword\CmsKeysController@_vAddCUT');
    Route::post('add-connect', 'Keyword\CmsKeysController@_pAddCUT')->name('add_connect');
    Route::get('add-connect-store', 'Keyword\CmsKeysController@_connectToStore');
    Route::post('add-connect-store', 'Keyword\CmsKeysController@_pConnectToStore')->name('add_connect_store');

    Route::post('/daterange/kw_crawled', 'Keyword\CmsKeysController@kw_crawled')->name('daterange.kw_crawled');

    Route::resource('posts', 'Posts\CmsPostController');
    Route::post('posts/{id}', 'Posts\CmsPostController@update');
    Route::post('ajax-posts', 'Posts\CmsPostController@show_svs')->name('svs_posts');

    

    
    Route::get('add-excel', 'Store\CmsStoreController@add')->name('stores.add_excel');
    Route::post('add-excel/stores', 'Store\CmsStoreController@_addTXT')->name('stores.add_excel_post');
    Route::get('export-excel', 'Store\CmsStoreController@export')->name('stores.export_excel');
    Route::post('export-excel', 'Store\CmsStoreController@_pexportAllURL')->name('stores.p_export');
    Route::post('store-remove/{id}', 'Store\CmsStoreController@destroy')->name('stores.destroy');
    Route::resource('stores', 'Store\CmsStoreController');
    Route::post('stores/{id}', 'Store\CmsStoreController@update');
    Route::post('ajax-stores', 'Store\CmsStoreController@svs_store')->name('all_stores');
    // route update stt
    Route::post('/update-store-stt','Store\CmsStoreController@_updateStt');


    Route::resource('syncs', 'Store\SyncsController');
    Route::post('syncs/{id}', 'Store\SyncsController@update');
    Route::post('all-sync','Store\SyncsController@stores_svs')->name('all_sync');

    Route::post('/sync-one','Store\SyncsController@_SyncOne');
    Route::post('/sync-start','Store\SyncsController@_startSync');
    Route::get('/sync-start','Store\SyncsController@_gstartSync');

    Route::resource('blacklist', 'BlacklistController');
    Route::post('ajax-blacklist', 'BlacklistController@show_svs')->name('svs_blacklist');

    Route::get('clear-cache/{cache_option?}/{slug_cache?}', 'CacheController@_clearCache');

    Route::get('run-bot', 'ScraperController@_index')->name('run_bot_keywords');

    Route::post('other-get-info', 'ScraperController@_getOtherInfo');
    Route::post('track-control', 'ScraperController@_trackControl');
    Route::post('track-bing', 'ScraperController@_bingPost')->name('bing_scraper');
    Route::post('track-google', 'ScraperController@_googleScraper')->name('google_scraper');
    Route::post('track-amz', 'ScraperController@_amzScraper')->name('amz_scraper');

    Route::get('bot-multi', 'ScraperController@_vBotMulti')->name('bot_multi');
    Route::post('get-keyword', 'ScraperController@_getKeyword');
    Route::post('add-2-sitemap', 'ScraperController@_add2Sitemap');

    Route::get('file-manager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('file-manager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');

});

Route::get('/{slug?}', 'Keyword\KeywordViewController@_viewKeyword')->name('v_keyword');

/*Migration DB
php artisan migrate --path=/database/migrations/2019_08_28_152107_create_categories_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_150242_create_spam_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_152854_create_results_collection.php
php artisan migrate --path=/database/migrations/2019_08_28_151618_create_keyword_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_131221_create_coupons_collection.php
php artisan migrate --path=/database/migrations/2019_09_13_135230_create_keys_related.php
db.categories.getIndexes();
*/

app/Tags.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Tags extends Eloquent
{
    use Sluggable;

    protected $collection = 'tags';
    protected $dates = ['created_at', 'updated_at'];
    protected $primaryKey = '_id';
    protected $guarded = [];
    public $type_id = ['tag' => 0, 'store_id' => 1, 'store_url' => 2, 'ref_info' => 3, 'ref_url' => 4];

    public function sluggable()
    {
        return [
            'tag_slug' => [
                'source' => 'tag_name'
            ]
        ];
    }
}

app/Http/Controllers/Tags/CmsTagsController.php
<?php

namespace App\Http\Controllers\Tags;

use App\Http\Controllers\Controller;
use App\Tags;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class CmsTagsController extends Controller
{
    private $cache_short = 5;
    private $cache_hourly = 60;
    private $cache_monthly = 60 * 24 * 30;

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $columns = array(
                0 => 'tag_type',
                1 => 'tag_name',
                2 => 'created_at',
                3 => 'options',
            );
            try {
                $limit = intval($request->input('length'));
                $start = $request->input('start');
                $order = $columns[$request->input('order.0.column')];
                $dir = $request->input('order.0.dir');
                $hash = md5($limit . $start . $order . $dir);

                $totalData = Cache::remember('totalData' . $hash, $this->cache_short, function () {
                    return Tags::count();
                });

                $totalFiltered = $totalData;

                if (empty($request->input('search.value'))) {
                    $posts = Cache::remember('tags' . $hash, $this->cache_short, function () use ($start, $limit, $order, $dir) {
                        return Tags::offset(intval($start))
                            ->take($limit)
                            ->orderBy($order, $dir)
                            ->get();
                    });
                } else {
                    $search = $request->input('search.value');
                    $hash = md5($limit . $start . $order . $dir . $search . "cat_list");
                    $posts = Cache::remember('tags' . $hash, $this->cache_short, function () use ($search, $start, $limit, $order, $dir) {
                        return Tags::where('tag_slug', 'LIKE', "%" . slugify($search) . "%")
                            ->offset(intval($start))
                            ->take($limit)
                            ->orderBy($order, $dir)
                            ->get();
                    });
                    $totalFiltered = Cache::remember('totalFiltered' . $hash, $this->cache_short, function () use ($search) {
                        return Tags::where('tag_slug', 'LIKE', "%" . slugify($search) . "%")
                            ->count();
                    });
                }
                $data = array();
                if (!empty($posts)) {
                    foreach ($posts as $post) {
                        $nestedData['tag_type'] = $post['tag_type'];
                        $nestedData['tag_name'] = $post['tag_name'] . '<small><br/>Id Tag: ' . $post['_id'] . '</small>';
                        $nestedData['created_at'] = 'Created at:' . Carbon::parse($post['created_at'])->format('d-m-Y H:m:s') . '<br/>Updated at:' . Carbon::parse($post['updated_at'])->format('d-m-Y H:m:s') . '<br/>';
                        $nestedData['options'] = '<a title="Edit: ' . $post['tag_name'] . '" href="' . route('cpanel.tags.edit', ['id' => $post['_id']]) . '"><span class="label label-primary"><i class="fa fa-edit"></i></span></a>
                        <a title="Remove: ' . $post['tag_name'] . '" href="' . route('cpanel.tags.destroy', $post['_id']) . '" data-id="' . $post['_id'] . '" data-name="' . $post['tag_name'] . '" data-method="delete" class="jquery-postback"><span class="label label-danger"><i class="fa fa-window-close"></i></span></a>';
                        $nestedData['_id'] = $post['_id'];
                        $data[] = $nestedData;
                    }
                }

                $json_data = array(
                    "draw" => intval($request->input('draw')),
                    "recordsTotal" => intval($totalData),
                    "recordsFiltered" => intval($totalFiltered),
                    "data" => $data,
                    "hash" => $hash,
                );
                echo json_encode($json_data);
            } catch (\Exception $e) {
                dd($e);
            }
        } else {
            return view('cpanel.tags.index_table');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('cpanel.tags.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        if ($request->tag_type == '') {
            return back(302)->withErrors(['Tag Type Null']);
        } else {
            try {
                $slug = slugify(trim($request->tag_name));
                $exits = Tags::where('tag_slug', $slug)->count();
                if ($exits > 0) {
                    return back(302)->withErrors(['Tag Name Exits']);
                } else {
                    $new_tag = new Tags();
                    $new_tag->tag_name = trim($request->tag_name);
                    $new_tag->tag_type = trim($request->tag_type);
                    $new_tag->save();
                }
                return redirect(route('cpanel.tags.index'), 302);
            } catch (\Exception $e) {
                dd($e);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        if ($id) {
            $editor = Tags::find($id);
            if ($editor) {
                return view('cpanel.tags.edit', compact(['editor']));
            } else {
                return back(302)->with('ID not found');
            }
        } else {
            return back(302)->with('Id not found');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        if ($id) {
            $update_tag = Tags::find($id);
            $update_tag->tag_name = trim($request->tag_name);
            $update_tag->tag_type = trim($request->tag_type);
            $update_tag->save();
            return back(302)->with('Updated success');
        } else {
            return back(302)->with('Update fail');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        if ($id) {
            Tags::where('_id', $id)->delete();
            return response()->json(['code' => 1, 'msg' => 'Deleted Success']);
        } else {
            return response()->json(['code' => 99, 'msg' => 'Fail']);
        }
    }
}

resources/views/cpanel/tags/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Add New Tags</h1>
@stop

@section('content')
    @if($errors->any())
        <p class="alert alert-error">{{$errors->first()}}</p>
    @endif
    <div class="col-12">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            {!! Form::open(['route' => 'cpanel.tags.store']) !!}
            {!! Form::token(); !!}
            <div class="box-body">
                <div class="form-group">
                    <label for="tag_type">Tag Type</label>
                    <select class="form-control" id="tag_type" name="tag_type">
                        <option value="job_type" selected>Job Type</option>
                        <option value="experience">Experience</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="tag_name">Tag Name</label>
                    <input type="text" class="form-control" name="tag_name" id="tag_name"
                           placeholder="include tag name"/>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('js')
@endsection

resources/views/cpanel/tags/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Edit Tag: {{$editor['tag_name']}}</h1>
@stop
@section('content')
    @if($errors->any())
        <p class="alert alert-error">{{$errors->first()}}</p>
    @endif
    <div class="col-12">
        <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{ route('cpanel.tags.update',['id' =>  $editor['_id'] ]) }}" method="post">
                {!! Form::token(); !!}
                <div class="box-body">
                    <div class="form-group">
                        <label for="tag_type">Tag Type</label>
                        <select class="form-control" id="tag_type" name="tag_type">
                            <option value="job_type" @if($editor['tag_type'] == 'job_type') selected @endif>Job Type
                            </option>
                            <option value="experience" @if($editor['tag_type'] == 'experience') selected @endif>
                                Experience
                            </option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tag_name">Tag Name</label>
                        <input type="text" class="form-control" name="tag_name" id="tag_name"
                               value="{{$editor['tag_name']}}"
                               placeholder="include tag name" disabled/>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/cpanel/tags/index_table.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1><i class="fa fa-tags"></i> List Tags</h1>
    <ol class="breadcrumb">
        <li><a href="/c-panel"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#" class="active">Tags</a></li>
    </ol>
    <br/>
    <a class="btn btn-success" href="{{route('cpanel.tags.create')}}">
        <i class=" fa fa-plus-circle"></i>
        Create New Tags
    </a>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
@stop

@section('content')
    @isset ($msg)
        <div class="alert alert-success">
            <p>{{ $msg }}</p>
        </div>
    @endisset
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Tag Type</th>
                <th>Tag Name</th>
                <th>Created At</th>
                <th>-</th>
            </tr>
            </thead>
        </table>
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#data-table').DataTable({
                "processing": true,
                "serverSide": true,
                "rowId": '_id',
                "ajax": {
                    "url": "{{ route('cpanel.tags.table') }}",
                    "dataType": "json",
                    "type": "POST",
                    "data": {_token: "{{csrf_token()}}"}
                },
                "columns": [
                    {"data": "tag_type"},
                    {"data": "tag_name"},
                    {"data": "created_at"},
                    {"data": "options"}
                ]
            });
        });
        $(document).on('click', 'a.jquery-postback', function (e) {
            e.preventDefault(); // does not go through with the link.
            let id = $(this).data('id'), name = $(this).data('id');
            $this = $(this);
            $.post({
                type: $this.data('method'),
                url: $this.attr('href')
            }).done(function (data) {
                alert('Success remove: ' + name);
                $("#" + id).hide();
            });
        });
    </script>
@endsection